name: Generate code coverage badge

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Coverage
        run: |
          go test -v ./test -covermode=count -coverpkg=./... -coverprofile=coverage.txt
        env:
          SECURE_PROXY: ${{ secrets.SECURE_PROXY }}
          NON_SECURE_PROXY: ${{ secrets.NON_SECURE_PROXY }}
          SOCKS5_PROXY: ${{ secrets.SOCKS5_PROXY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Noooste/azuretls-client